In [2]:
import numpy as np

1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [4]:
a = np.array([10,7,5,90,100])
a

array([ 10,   7,   5,  90, 100])

2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.

In [7]:
a = np.arange(100,201)
a_1 = a[::2]
a_1

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [8]:
b = np.zeros_like(a_1)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)

In [16]:
c = np.arange(1001, 10001)
c[c % 100 == 0].reshape(3,3,10)

array([[[ 1100,  1200,  1300,  1400,  1500,  1600,  1700,  1800,  1900,
          2000],
        [ 2100,  2200,  2300,  2400,  2500,  2600,  2700,  2800,  2900,
          3000],
        [ 3100,  3200,  3300,  3400,  3500,  3600,  3700,  3800,  3900,
          4000]],

       [[ 4100,  4200,  4300,  4400,  4500,  4600,  4700,  4800,  4900,
          5000],
        [ 5100,  5200,  5300,  5400,  5500,  5600,  5700,  5800,  5900,
          6000],
        [ 6100,  6200,  6300,  6400,  6500,  6600,  6700,  6800,  6900,
          7000]],

       [[ 7100,  7200,  7300,  7400,  7500,  7600,  7700,  7800,  7900,
          8000],
        [ 8100,  8200,  8300,  8400,  8500,  8600,  8700,  8800,  8900,
          9000],
        [ 9100,  9200,  9300,  9400,  9500,  9600,  9700,  9800,  9900,
         10000]]])

5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [20]:
d = np.ones((4,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
20, 90, 80, 100, -20, 30
50, -10, 25, 120, -40, 90

In [34]:
a = np.array([20,90,80,100,-20,30])
b = np.array([50,-10,25,120,-40,90])
print(np.ndim(a), np.ndim(b))
print(np.shape(a), np.shape(b))
print(a.size, b.size)

1 1
(6,) (6,)
6 6


7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [39]:
a = np.random.randn(42).reshape(3,2,7)

array([[[-0.51314324,  1.68651147,  0.19187113,  0.21851338,
          0.02042964, -1.35968106,  1.07474278],
        [ 0.43983493,  0.17439709, -0.91601585,  0.99570194,
         -0.27892281, -1.25276837,  1.14308649]],

       [[ 0.71650335, -0.97346501,  0.23860854,  2.24339728,
         -1.14507645, -0.49673428,  1.77522918],
        [ 0.31354509, -0.48476618,  0.70588377,  0.86940295,
         -1.75679076,  0.73512007,  1.96809704]],

       [[-0.08518937,  0.17076112, -0.27276042,  0.32643172,
          0.35442499,  0.69021368,  0.59722694],
        [-0.37120276,  1.70795266, -1.42358808, -1.79251748,
          0.96392672,  0.92799931,  0.01029203]]])

8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [42]:
a = np.random.randint(1, 100, size=(4,5))
np.save('arr.npy', a)

9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [50]:
a__ = np.load('arr.npy')
a__

array([[ 9, 90, 84, 60, 66],
       [67,  7, 29, 84, 52],
       [80, 79, 48, 16, 23],
       [51, 33, 89, 92, 75]])

10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [56]:
print(np.sum(a__))
print(np.sum(a__, axis=0))
print(np.sum(a__, axis=1))

1134
[207 209 250 252 216]
[309 239 246 340]


11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [61]:
a = np.arange(1, 51).reshape(5,10)
a>25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [62]:
np.sum(a>25)

25

12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [65]:
z = np.arange(0,30).reshape(5,6)
z

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

12. index (1,1), (2,3), (1,5)의 값들 조회

In [64]:
z[1,1], z[2,3], z[1,5]

(7, 15, 11)

13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

In [71]:
z1 = z[1:4, 1:4]
z1

array([[ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [72]:
z1[::-1]

array([[19, 20, 21],
       [13, 14, 15],
       [ 7,  8,  9]])

15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [80]:
z2 = z[z>=15]
z2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
np.sum(z2)/np.sum(z>=15)

22.0

16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력

In [87]:
np.argwhere(z>=15)

array([[2, 3],
       [2, 4],
       [2, 5],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5],
       [4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [4, 5]], dtype=int64)

17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [109]:
np.fliplr(z)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [121]:
x = np.arange(1, 7).reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.

In [114]:
x1 = x.reshape(1,3,2)
x1

array([[[1, 2],
        [3, 4],
        [5, 6]]])

19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [115]:
x2 = x.reshape(1,3,2,1)
x2

array([[[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]]])

20. 배열을 1차원 배열로 변환한 배열을 생성.

In [116]:
x3 = x.flatten()
x3

array([1, 2, 3, 4, 5, 6])

21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))

In [128]:
x4 = np.append(x, [[1,1], [2,2]], axis=0)
x4.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [2, 2]])

22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.

In [151]:
scores = [
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [144]:
np.shape(scores)

(5, 4)

22. 각 과목별 평균점수를 조회.

In [159]:
과목 = np.mean(scores, axis=0)
print(과목)

[66. 70. 70. 78.]


23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [162]:
scores_1 = np.append(scores, 과목)
scores_1.reshape(6,4)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

24. 각 학생들의 평균 점수 조회

In [163]:
학생평균 = np.mean(scores, axis=1)
학생평균

array([75. , 85. , 67.5, 57.5, 70. ])

25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [169]:
max_score = np.argmax(scores, axis=1)
max_score+1

array([4, 3, 1, 2, 4], dtype=int64)

26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [171]:
min_score = np.argmin(scores, axis=0)
min_score+1

array([4, 5, 1, 3], dtype=int64)

27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회

In [176]:
편차 = np.std(scores, axis=1)
np.argmax(편차), np.argmin(편차)

(4, 1)

28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [177]:
학생편차 = np.std(scores, axis=0)
np.argmax(학생편차), np.argmin(학생편차)

(3, 2)

29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.

In [179]:
A = [
  [1,2,3],
  [4,5,6],
  [7,8,9]
]

B = [
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

29. 두 배열을 수직방향으로 합치기. 

In [181]:
AB = np.concatenate([A, B], axis=0)
AB

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.

In [183]:
C = np.split(AB, [2])
C

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [184]:
s = [10, 50, 75, 20, 70, 50, 80]

31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [187]:
avg = np.mean(s)
avg
np.sum(s>=avg)

3

32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [188]:
np.sum(s>=avg)/7

0.42857142857142855

33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [207]:
salary = [7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420, 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120, 7100, 5220, 8810, 253000]
salary = np.array(salary)

# 왜 리스트에서 array로 변환이 안되는지 모르겠습니다ㅠㅜㅠ덕분에 아래 문제들도 실행이 안되네요.....ㅠ

TypeError: 'list' object is not callable

 33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [205]:
np.quantile(salary, q=0.75)

TypeError: 'list' object is not callable

34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [ ]:
np.quantile(salary, q=0.25)

35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.

In [ ]:
avg = np.mean(salary)
median = np.median(salary)

중앙값